language: cpp

compiler: gcc

sudo: false

addons:
    apt:
        packages:
	- cmake

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    email:
        - czerniecki.wojciech@gmail.com
    on_success: change
    on_failure: always

