sudo: false

language: cpp

compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - build-essential
      - libxrandr-dev
      - libx11-dev
      - libxxf86vm-dev
      - libxi-dev

env: COMPILER=g++-4.8

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    email:
        - czerniecki.wojciech@gmail.com
    on_success: change
    on_failure: always

