sudo: false
language: c
os: linux
compiler: gcc-5

addons:
  apt:
    packages:
      - cmake
      - build-essential
      - libxrandr-dev
      - libx11-dev
      - libxxf86vm-dev
      - libxi-dev
      - gcc-5

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    email:
        - czerniecki.wojciech@gmail.com
    on_success: change
    on_failure: always

