sudo: false

language: cpp

compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - xrandr
      - x11
      - Xxf86vm
      - m
      - Xi

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    email:
        - czerniecki.wojciech@gmail.com
    on_success: change
    on_failure: always

