sudo: false

language: cpp

compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - libxrandr-dev
      - libx11-dev
      - libxxf86vm-dev
      - libxi-dev

matrix:
  include:
      - os: linux
        compiler: gcc-4.9

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    email:
        - czerniecki.wojciech@gmail.com
    on_success: change
    on_failure: always

