sudo: false
language: cpp
os: linux
compiler: gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    packages:
      - cmake
      - build-essential
      - libxrandr-dev
      - libx11-dev
      - libxxf86vm-dev
      - libxi-dev
      - gcc-4.8
      - g++-4.8

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    email:
        - czerniecki.wojciech@gmail.com
    on_success: change
    on_failure: always

